### ISSUE TITLE
C calculator 

### ISSUE THREAD

**Issue by buddhimac111** [buddhimac111/hacktoberfest2023-open-tasks#2]
Design a simple calculator program in C that can perform basic arithmetic operations such as addition, subtraction, multiplication, and division. The program should take user input for two numbers and the desired operation, and then display the result. (Improve it if you want)

**Comment by MeetD99** [comment]
I would like to work on this issue, Can you assign it to me please?

**Comment by buddhimac111** [comment]
@MeetD99 This repository is designed for students to gain an understanding of open-source contributions. There's no need for an assign for this issue; simply read the repository's README and follow the provided instructions. I'll review your code and merge it..

**Comment by MeetD99** [comment]
I have successfully created a PR @buddhimac111 . Kindly Review it and lemme know of any changes. Thank You!
